EMEP/Models/Consulta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consulta()
        {
            this.RegistrarCita = new HashSet<RegistrarCita>();
        }
    
        public int id { get; set; }
        public int ID_MEDICO { get; set; }
        public int ID_CONSULTORIO { get; set; }
        public decimal precio { get; set; }
        public int ID_ESPECIALIDAD { get; set; }
    
        public virtual Consultorio Consultorio { get; set; }
        public virtual Especialidad Especialidad { get; set; }
        public virtual Medico Medico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrarCita> RegistrarCita { get; set; }
    }
}

EMEP/Controllers/ConsultaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMEP.Models;
using PagedList;


namespace EMEP.Controllers
{
    public class ConsultaController : Controller
    {
        private EMEPEntities db = new EMEPEntities();

        // GET: Consulta EMEP
        public ActionResult Index(string dato, string buscar, string filtro, int? page)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            ViewBag.actual = dato;
            ViewBag.Medico1 = string.IsNullOrEmpty(dato) ? "medico" : "";
            ViewBag.Espe1 = dato == "Especialidad" ? "esp" : "Especialidad";

            if (buscar != null)
            {
                page = 1;
            }
            else
            {
                buscar = filtro;
            }

            ViewBag.filtroActual = buscar;

            var consulta = from co in db.Consulta
                           select co;
            if (!string.IsNullOrEmpty(buscar))
            {
                consulta = consulta.Where(co => co.Medico.nombre.Contains(buscar)
               || co.Medico.nombre.Contains(buscar)
               || co.Medico.p_Apellido.Contains(buscar)
               || co.Medico.s_Apellido.Contains(buscar)
               || co.Especialidad.descripcion.Contains(buscar)
               || co.Consultorio.numero.Contains(buscar)
               || co.precio.ToString().Contains(buscar));
            }

            switch (dato)
            {
                case "medico":
                    consulta = consulta.OrderByDescending(co => co.Medico.nombre);
                    break;
                case "Especialidad":
                    consulta = consulta.OrderBy(co => co.Especialidad.descripcion);
                    break;
                case "esp":
                    consulta = consulta.OrderByDescending(co => co.Especialidad.descripcion);
                    break;
                default:
                    consulta = consulta.OrderBy(co => co.Medico.nombre);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(consulta.ToPagedList(pageNumber, pageSize));
        }



        // GET: Consulta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique una consulta";
                return RedirectToAction("Index");
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                TempData["mensaje"] = "No existe la consulta";
                return RedirectToAction("Index");
            }
            return View("Details", consulta);
        }

        // GET: Consulta/Create
        public ActionResult Create()
        {
            ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion");
            ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion");
            ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM");
            return View("Create");
        }

        // POST: Consulta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Consulta consulta)
        {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            
            var existe = from ex in db.Consulta
                         select ex;

            bool validar1 = existe.Any(ex => ex.ID_MEDICO== consulta.ID_MEDICO);           
            bool validar2 = existe.Any(ex => ex.ID_CONSULTORIO == consulta.ID_CONSULTORIO);
            bool validar3 = existe.Any(ex => ex.ID_ESPECIALIDAD == consulta.ID_ESPECIALIDAD);

            if (validar1 == true)
            {
               
                ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM",consulta.ID_MEDICO);
                ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
                ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
                TempData["mensaje"] = "El medico ya se encuantra ocupado. Seleccione otro Medico.";
                return View("Create", consulta);
            }


            if (validar2 == true)
            {
                ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM", consulta.ID_MEDICO);
                ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
                ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
                TempData["mensaje"] = "La consultorio ya se encuantra ocupado. Seleccione otro consultorio.";
                return View("Create", consulta);
            }

            if (validar3 == true) { 
            
               
                ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM", consulta.ID_MEDICO);
                ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
                ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
                TempData["mensaje"] = "La especialidad ya se encuantra ocupada. Seleccione otra especiallidad.";
                return View("Create", consulta);
            }

           

            try
            {
                db.Consulta.Add(consulta);
                db.SaveChanges();
                TempData["mensaje"] = "Consulta guardada satisfactoriamente!";
                return RedirectToAction("Index");
            }
            catch 
            {



                ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
                ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
                ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM", consulta.ID_MEDICO);
                TempData["mensaje"] = "Consulta NO registrada";
                return View("Create", consulta);
            }
        }

        // GET: Consulta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique la consulta";
                return RedirectToAction("Index");
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                TempData["mensaje"] = "No existe la consulta";
                return RedirectToAction("Index");
            }
            ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
            ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
            ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM", consulta.ID_MEDICO);
            return View("Edit", consulta);
        }

        // POST: Consulta/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Consulta consulta)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            try
            {
                db.Entry(consulta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch 
            {
                TempData["mensaje"] = "El tour no se logro actualizar";
                ViewBag.listaConsultorio = new SelectList(db.Consultorio, "id", "descripcion", consulta.ID_CONSULTORIO);
                ViewBag.listaEspecialidad = new SelectList(db.Especialidad, "id", "descripcion", consulta.ID_ESPECIALIDAD);
                ViewBag.listaMedicos = new SelectList(db.Medico, "id", "NombreCompletoM", consulta.ID_MEDICO);
                return View("Edit", consulta);
            }       
        }

        // GET: Consulta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }

        // POST: Consulta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consulta consulta = db.Consulta.Find(id);
            db.Consulta.Remove(consulta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMEP/Views/Consulta/Create.cshtml
@model EMEP.Models.Consulta

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Crear Consulta</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_MEDICO, "Médico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_MEDICO,
              (SelectList)ViewBag.listaMedicos, "Seleccione a un Medico",
              htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ID_MEDICO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_CONSULTORIO, "Consultorio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_CONSULTORIO,
              (SelectList)ViewBag.listaConsultorio, "Seleccione a un Consultorio",
              htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ID_CONSULTORIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ESPECIALIDAD, "Especialidad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_ESPECIALIDAD,
              (SelectList)ViewBag.listaEspecialidad, "Seleccione a una Especialidad",
              htmlAttributes: new { @class = "form-control" })


                @Html.ValidationMessageFor(model => model.ID_ESPECIALIDAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Consulta")'">
        Regresar
    </button>
</div>


EMEP/Views/Consulta/Delete.cshtml
@model EMEP.Models.Consulta

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consulta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consultorio.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultorio.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medico.correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medico.correo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EMEP/Views/Consulta/Details.cshtml
@model EMEP.Models.Consulta

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Detalle de Consulta</h2>
<br />

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Medico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medico.nombre)
            @Html.DisplayFor(model => model.Medico.p_Apellido)
            @Html.DisplayFor(model => model.Medico.s_Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Consultorio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Consultorio.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.precio)
        </dd>
    </dl>
</div>
<p>
    <button type="button" class="btn btn-outline-primary"
            onclick="location.href='@Url.Action("Edit", "Consulta",new { id = Model.id })'">
        Editar
    </button>

    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Consulta")'">
        Regresar
    </button>
</p>

EMEP/Views/Consulta/Edit.cshtml
@model EMEP.Models.Consulta

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Editar Consulta</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_MEDICO, "Médico", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_MEDICO,
              (SelectList)ViewBag.listaMedicos, "Seleccione a un Médico",
              htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ID_MEDICO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_CONSULTORIO, "Consultorio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_CONSULTORIO,
              (SelectList)ViewBag.listaConsultorio, "Seleccione a un Consultorio",
              htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ID_CONSULTORIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_ESPECIALIDAD, "Especialidad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ID_ESPECIALIDAD,
              (SelectList)ViewBag.listaEspecialidad, "Seleccione a una Especialidad",
              htmlAttributes: new { @class = "form-control" })

                @Html.ValidationMessageFor(model => model.ID_ESPECIALIDAD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Consulta")'">
            Regresar
        </button>
    </div>
</div>

EMEP/Views/Consulta/Index.cshtml
@model PagedList.IPagedList<EMEP.Models.Consulta>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Consulta</h2>

<p>
    <button type="button" class="btn btn-outline-info"
            onclick="location.href='@Url.Action("Create", "Consulta")'">
        Nuevo
    </button>
</p>

@using (Html.BeginForm("Index", "Consulta", FormMethod.Get))
{
    <p>
        Ingresar el dato: @Html.TextBox("buscar", ViewBag.filtroActual as string)
        <input type="submit" value="Buscar" />
    </p>
}

<table class="table">

    <tr>
        <th>

            @Html.ActionLink("Medico", "Index", new { dato = ViewBag.Medico1, filtro = ViewBag.filtroActual })
        </th>
        <th>

            @Html.ActionLink("Especialidad", "Index", new { dato = ViewBag.Espe, filtro = ViewBag.filtroActual })
        </th>
        <th>
            Consultorio

        <th>

            Precio
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>

                @Html.DisplayFor(modelItem => item.Medico.NombreCompletoM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad.descripcion)
            </td>
            <td style="text-align:center;">

                @Html.DisplayFor(modelItem => item.Consultorio.numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<br />
Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, dato = ViewBag.actual, filtro = ViewBag.filtroActual }))


<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Consulta")'">
            Regresar
        </button>
    </div>
</div>