EMEP/Models/Especialidad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Especialidad()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}

EMEP/Controllers/EspecialidadController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMEP.Models;
using PagedList;

namespace EMEP.Controllers
{
    public class EspecialidadController : Controller
    {
        private EMEPEntities db = new EMEPEntities();

        public ActionResult Index(string dato, string buscar, string filtro, int? page)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            ViewBag.actual = dato;

            ViewBag.Descripcion1 = dato == "Descripcion" ? "des" : "Descripcion";

            if (buscar != null)
            {
                page = 1;
            }
            else
            {
                buscar = filtro;
            }

            ViewBag.filtroActual = buscar;

            var especialidad = from es in db.Especialidad
                               select es;

            if (!string.IsNullOrEmpty(buscar))
            {
                especialidad = especialidad.Where(es => es.descripcion.Contains(buscar));
            }


            switch (dato)
            {

                case "des":
                    especialidad = especialidad.OrderByDescending(es => es.descripcion);
                    break;
                default:
                    especialidad = especialidad.OrderBy(es => es.descripcion);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);

            return View(especialidad.ToPagedList(pageNumber, pageSize));
        }

        // GET: Especialidad/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique la Especialidad";
                return RedirectToAction("Index");
            }
            Especialidad especialidad = db.Especialidad.Find(id);
            if (especialidad == null)
            {
                TempData["mensaje"] = "No existe la Especialidad";
                return RedirectToAction("Index");
            }
            return View("Details", especialidad);
        }

        // GET: Especialidad/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Especialidad/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Especialidad objEspe)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            try
            {
                db.Especialidad.Add(objEspe);
                db.SaveChanges();
                TempData["mensaje"] = "Especialidad guardado satisfactoriamente!";
                return RedirectToAction("Index");
            }
            catch
            {
                TempData["mensaje"] = "Especilaidad NO registrado";
                return View(objEspe);
            }
        }

        // GET: Especialidad/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique una Especialidad";
                return RedirectToAction("Index");
            }
            Especialidad especialidad = db.Especialidad.Find(id);
            if (especialidad == null)
            {
                TempData["mensaje"] = "No existe la Especialidad";
                return RedirectToAction("Index");
            }
            return View("Edit",especialidad);
        }

        // POST: Especialidad/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Especialidad objEsp)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            try
            {
                db.Entry(objEsp).State = EntityState.Modified;
                db.SaveChanges();

                TempData["mensaje"] = "Especialidad actualizado satisfactoriamente!";
                return RedirectToAction("Index");
            }
            catch
            {

                TempData["mensaje"] = "La Especilaidad no se logro actualizar";
                return View("Edit", objEsp);
            }


        }

        // GET: Especialidad/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especialidad especialidad = db.Especialidad.Find(id);
            if (especialidad == null)
            {
                return HttpNotFound();
            }
            return View(especialidad);
        }

        // POST: Especialidad/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Especialidad especialidad = db.Especialidad.Find(id);
            db.Especialidad.Remove(especialidad);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMEP/Views/Especialidad/Create.cshtml
@model EMEP.Models.Especialidad

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Crear Especialidad</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Especialidad")'">
        Regresar
    </button>
</div>

EMEP/Views/Especialidad/Delete.cshtml
@model EMEP.Models.Especialidad

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Especialidad</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EMEP/Views/Especialidad/Details.cshtml
@model EMEP.Models.Especialidad

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Detalle de Especialidad</h2>
<br />

<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

    </dl>
</div>

<p>
    <button type="button" class="btn btn-outline-primary"
            onclick="location.href='@Url.Action("Edit", "Especialidad",new { id = Model.id })'">
        Editar
    </button>

    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Especialidad")'">
        Regresar
    </button>
</p>

EMEP/Views/Especialidad/Edit.cshtml
@model EMEP.Models.Especialidad

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Editar Especialidad</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Especialidad")'">
            Regresar
        </button>
    </div>
</div>

EMEP/Views/Especialidad/Index.cshtml


@model PagedList.IPagedList<EMEP.Models.Especialidad>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Especialidad</h2>

<p>
    <button type="button" class="btn btn-outline-info"
            onclick="location.href='@Url.Action("Create", "Especialidad")'">
        Nuevo
    </button>
</p>

@using (Html.BeginForm("Index", "Especialidad", FormMethod.Get))
{
    <p>
        Ingresar el dato: @Html.TextBox("buscar", ViewBag.filtroActual as string)
        <input type="submit" value="Buscar" />

    </p>
}



<table class="table">

    <tr>
        <th>
            @Html.ActionLink("Descripción", "Index", new { dato = ViewBag.Descripcion1, filtro = ViewBag.filtroActual })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>

<br />
Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, dato = ViewBag.actual, filtro = ViewBag.filtroActual }))

<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Especialidad")'">
            Regresar
        </button>
    </div>
</div>