EMEP/Models/Consultorio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultorio()
        {
            this.Consulta = new HashSet<Consulta>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string numero { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }
    }
}

EMEP/Controllers/ConsultorioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMEP.Models;
using PagedList;

namespace EMEP.Controllers
{
    public class ConsultorioController : Controller
    {
        private EMEPEntities db = new EMEPEntities();

        // GET: Consultorios
        public ActionResult Index(string dato, string buscar, string filtro, int? page)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            ViewBag.actual = dato;
            ViewBag.Descripcion1 = string.IsNullOrEmpty(dato) ? "des" : "";
            ViewBag.Numero1 = dato == "Numero" ? "num" : "Numero";

            if (buscar!= null)
            {
                page = 1;
            }
            else
            {
                buscar = filtro;
            }

            ViewBag.filtroActual = buscar;

            var consultorio = from co in db.Consultorio
                              select co;

            if (!string.IsNullOrEmpty(buscar))
            {
                consultorio = consultorio.Where(co => co.descripcion.Contains(buscar)
                  || co.numero.Contains(buscar));
            }

            switch (dato)
            {
                case "des":
                    consultorio = consultorio.OrderByDescending(co => co.descripcion);
                    break;
                case "Numero":
                    consultorio = consultorio.OrderBy(co => co.numero);
                    break;
                case "num":
                    consultorio = consultorio.OrderByDescending(co => co.numero);
                    break;
                default:
                    consultorio = consultorio.OrderBy(co => co.descripcion);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(consultorio.ToPagedList(pageNumber,pageSize));
        }

        // GET: Consultorio/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique un Consultorio";
                return RedirectToAction("Index");
            }
            Consultorio consultorio = db.Consultorio.Find(id);
            if (consultorio == null)
            {
                TempData["mensaje"] = "No existe el Consultorio";
                return RedirectToAction("Index");
            }
        
            return View("Details", consultorio);
        }

        // GET: Consultorio/Crear
        public ActionResult Create()
        {
            return View();
        }

        // POST: Consultorio/Crear
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Models.Consultorio objConsul)   
     {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            try
            {
                db.Consultorio.Add(objConsul);
                db.SaveChanges();
                TempData["mensaje"] = "Consultorio guardado satisfactoriamente!";
                return RedirectToAction("Index");
            }
            catch (Exception)
            {

                TempData["mensaje"] = "Consultorio NO registrado";
                return View(objConsul);
            }
        }

        // GET: Consultorio/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                TempData["mensaje"] = "Especifique un Consultorio";
                return RedirectToAction("Index");
            }
            Consultorio consultorio = db.Consultorio.Find(id);
            if (consultorio == null)
            {
                TempData["mensaje"] = "No existe el Consulotorio";
                return RedirectToAction("Index");
            }
            return View("Edit",consultorio);
        }

        // POST: Consultorio/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Consultorio objCon)
        {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            try
            {
                db.Entry(objCon).State = EntityState.Modified;
                db.SaveChanges();
                TempData["mensaje"] = "Consultorio actualizado satisfactoriamente!";
                return RedirectToAction("Index");
            }
            catch 
            {

                TempData["mensaje"] = "El Consultorio no se logro actualizar";
                return View("Edit",objCon);
            }
        }

        // GET: Consultorio/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consultorio consultorio = db.Consultorio.Find(id);
            if (consultorio == null)
            {
                return HttpNotFound();
            }
            return View(consultorio);
        }

        // POST: Consultorio/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Consultorio consultorio = db.Consultorio.Find(id);
            db.Consultorio.Remove(consultorio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMEP/Views/Consultorio/Create.cshtml
@model EMEP.Models.Consultorio

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Crear Consultorio</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}


<div>
    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Consultorio")'">
        Regresar
    </button>
</div>

EMEP/Views/Consultorio/Delete.cshtml
@model EMEP.Models.Consultorio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consultorio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EMEP/Views/Consultorio/Details.cshtml
@model EMEP.Models.Consultorio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Detalle de Consultorio</h2>
<br />
<div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

    </dl>
</div>
<p>
    <button type="button" class="btn btn-outline-primary"
            onclick="location.href='@Url.Action("Edit", "Consultorio",new { id = Model.id })'">
        Editar
    </button>

    <button type="button" class="btn btn-outline-success"
            onclick="location.href='@Url.Action("Index", "Consultorio")'">
        Regresar
    </button>
</p>

EMEP/Views/Consultorio/Edit.cshtml
@model EMEP.Models.Consultorio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<br />
<h2>Editar Consultorio</h2>
<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Consultorio")'">
            Regresar
        </button>
    </div>
</div>

EMEP/Views/Consultorio/Index.cshtml

@model PagedList.IPagedList<EMEP.Models.Consultorio>
@using PagedList.Mvc;

<link href="~/Content/PagedList.css" rel="stylesheet" />


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAD.cshtml";
}

<h2>Consultorio</h2>

<p>
    <button type="button" class="btn btn-outline-info"
            onclick="location.href='@Url.Action("Create", "Consultorio")'">
        Nuevo
    </button>
</p>

@using (Html.BeginForm("Index", "Consultorio", FormMethod.Get))
{
    <p>
        Ingresar el dato: @Html.TextBox("buscar", ViewBag.filtroActual as string)
        <input type="submit" value="Buscar" />
    </p>
}


<table class="table">
    <tr>
        <th>

            @Html.ActionLink("Descripción", "Index", new { dato = ViewBag.Descripcion1, filtro = ViewBag.filtroActual })

        </th>

        <th>

            @Html.ActionLink("Numero", "Index", new { dato = ViewBag.Numero1, filtro = ViewBag.filtroActual })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numero)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = item.id }) |
                @Html.ActionLink("Detalles", "Details", new { id = item.id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>
<br />
Pagina @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) de @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, dato = ViewBag.actual, filtro = ViewBag.filtroActual }))

<div class="form-group">
    <div>
        <button type="button" class="btn btn-outline-success"
                onclick="location.href='@Url.Action("Index", "Consultorio")'">
            Regresar
        </button>
    </div>
</div>

